### ISSUE TITLE
Add pr0p0ll-viewer

### ISSUE THREAD

**Issue by Scarwolf** [holzmaster/userscripts#36]
See:
https://pr0gramm.com/user/PoTTii/uploads/3083479
https://github.com/Scarwolf/pr0p0ll-viewer

pr0p0ll-Viewer is a tool which takes the results in the JSON Format provided by pr0p0ll and generates a Webpage containing one chart per poll. It's possible to take a screenshot with the click of a button that is ready to be uploaded on pr0gramm.

It is in active development.

**Comment by RundesBalli** [comment]
This project has been added here:
https://github.com/holzmaster/userscripts/commit/8d730c4e43ac568170b82fd798fc06d1ee1f796a

@holzmaster this issue can be closed.
