### ISSUE TITLE
Neues Userscript: dailyBr0t

### ISSUE THREAD

**Issue by pr0stats** [holzmaster/userscripts#6]
Siehe pr0stats/pr0kular-feedback#4.

**Comment by holzmaster** [comment]
Was ist der Status hiervon? @Bachstelze @pr0stats

**Comment by FlorianMaak** [comment]
Das Repository https://github.com/Bachstelze/pr0gramm_spider existiert nicht mehr. Auf diesem stützt sich jedoch das Feedback, welches hätte ergänzt werden sollen.

Ich denke, dass man an dieser Stelle "zu machen" kann.
